### ISSUE TITLE
[docs] minor updates required on README 

### ISSUE THREAD

**Issue by alxiong** [defi-wonderland/solidity-boilerplate#27]
README.md needs some updates:
1. need to add the step of filling`.env` with Alchemy tokens in order to even run `yarn test` successfully (since it involved mainnet forking)
2. `yarn lint` is not a valid script, only `yarn lint:check` or `yarn lint:fix` are (based on current `main`: 0a30e58770720c2be91a738f7c4bc9aae51b4438)

Another issue I run into:
```
└─○ yarn docs
yarn run v1.22.11
warning package.json: No license field
$ solidity-docgen --solc-module solc-0.8
    Error: Solidity was unable to compile. contracts/Greeter.sol:2:1: ParserError: Source file requires different compiler version (current compiler is 0.7.5+commit.eb77ed08.Emscripten.clang) - note that nightly builds
     are considered to be strictly less than the released version
    pragma solidity >=0.8.4 <0.9.0;
    ^-----------------------------^
     (And 1 other errors...)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
^^ I think you try to reproduce this with a fresh new clone.

**Comment by turtlemoji** [comment]
Thanks! this should be addressed in these PR's now:
1) #69 
2) #70

We should create a new issue for the yarn docs
