### ISSUE TITLE
[question] hardhat config

### ISSUE THREAD

**Issue by alxiong** [defi-wonderland/solidity-boilerplate#28]
1. why manually probing into `hardhat/types::HardhatUserConfig` and declaring the `outputSelection` rather awkwardly [here](https://github.com/defi-wonderland/solidity-boilerplate/blob/main/hardhat.config.ts#L90-L99), instead of using [`hardhat-storage-layout` plugin](https://hardhat.org/plugins/hardhat-storage-layout.html)
2. where in the code did we try to update a storage slot in the example code or test?

**Comment by alxiong** [comment]
Ah! I think I was mistaken, we were not intending to use `hardhat-storage-layout` plugin, but rather [`smock`](https://smock.readthedocs.io/en/latest/getting-started.html) instead, correct?

Nevertheless, should have stick to: 
```js
const config = {
  solidity: {
    settings: {
      outputSelection: {
        "*": {
          "*": ["storageLayout"]
        }
      }
    }
  }
}
```
instead of 
```ts
  (config.solidity as MultiSolcUserConfig).compilers = (config.solidity as MultiSolcUserConfig).compilers.map((compiler) => {
    return {
      ...compiler,
      outputSelection: {
        '*': {
          '*': ['storageLayout'],
        },
      },
    };
  });
```

**Comment by alxiong** [comment]
More questions/comments:

possible updates to `hardhat.config.ts` to consider:

1. add`gasReporter.excludeContracts: ['contracts/mocks/']`

puzzling devDependencies:

1. when is `moment` ever used? plus the package is [in maintenance mode](https://momentjs.com/docs/#/-project-status/)

**Comment by 404skillz** [comment]
@alxiong thanks for all the input ! It got lost on my notifications. Will look into all of them and ping you back !

**Comment by turtlemoji** [comment]
> More questions/comments:
> 
> possible updates to `hardhat.config.ts` to consider:
> 
> 1. add`gasReporter.excludeContracts: ['contracts/mocks/']`
> 
> puzzling devDependencies:
> 
> 1. when is `moment` ever used? plus the package is [in maintenance mode](https://momentjs.com/docs/#/-project-status/)

- Moment is removed in current main
- Agree with the gas reporter
Now it should be `excludeContracts: ['solidity/mocks/'],`

**Comment by 0xged** [comment]
hey guys! in terms of the contract exclusion of `mocks`, the bad thing is that if you test against `mocks` contracts you will not have any of your tests in the coverage.

**Comment by turtlemoji** [comment]
@0xged True, closing for now then.
